name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: macos-15
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 选择Xcode版本（用Runner里实际有的版本）
        run: |
          LATEST_XCODE=$(ls /Applications | grep Xcode | sort -V | tail -n 1)
          sudo xcode-select -s /Applications/$LATEST_XCODE
          xcodebuild -version
      - name: 构建项目（跳过签名）
        run: |
          xcodebuild -project MyClean.xcodeproj -scheme MyClean -destination 'platform=macOS,arch=arm64' CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" build
      # - name: 运行测试（如果有测试用例，否则可以注释掉）
      #   run: |
      #     xcodebuild -project MyClean.xcodeproj -scheme MyClean -destination 'platform=macOS,arch=arm64' test
